apiVersion: akodns.vmware.com/v1
kind: AVIDnsRecord
metadata:
  name: test
spec:
  fqdn: "test.example.local"
  ttl: 300
  rtype: DNS_RECORD_A
  ip_address:
    - ip_address:
        addr: 192.168.1.112
        type: "V4"
    - ip_address:
        addr: 192.168.1.113
        type: "V4"
