apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: avidnsrecords.akodns.vmware.com
spec:
  group: akodns.vmware.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - fqdn
                - rtype
              properties:
                fqdn:
                  type: string
                ttl:
                  type: integer
                rtype:
                  type: string
                  enum:
                    - DNS_RECORD_A
                    - DNS_RECORD_AAA
                ip_address:
                  type: array
                  items:
                    type: object
                    properties:
                      ip_address:
                        type: object
                        properties:
                          addr:
                            type: string
                          type:
                            type: string
  scope: Namespaced
  names:
    plural: avidnsrecords
    singular: avidnsrecord
    kind: AVIDnsRecord
    shortNames:
      - adr