apiVersion: apps/v1
kind: Deployment
metadata:
  name: avidnsoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avidnsoperator
  template:
    metadata:
      labels:
        app: avidnsoperator
    spec:
      serviceAccountName: avi-dns-controller
      containers:
      - name: avidnsoperator
        image: jhasensio/avidnsoperator:1.0
        ports:
        stdin: true
        tty: true
        volumeMounts:
          - name: config-volume
            mountPath: /config/controller_config.yaml
            subPath: controller_config.yaml
          - name: secret-volume
            mountPath: /config/controller_secret.yaml
            subPath: controller_secret.yaml
      volumes:
        - name: config-volume
          configMap:
            name: dns-controller-config
        - name: secret-volume
          secret:
            secretName: dns-controller-secret
