apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-tools
  template:
    metadata:
      labels:
        app: ubuntu-tools
    spec:
      containers:
      - name: ubuntu-tools
        image: python:3.11-slim
        ports:
        - containerPort: 5000
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt update && \
            apt install -y vim nano curl git procps netcat-openbsd iputils-ping && \
            pip install kopf avisdk pyyaml && \
            tail -f /dev/null
        stdin: true
        tty: true
        volumeMounts:
            - name: config-volume
              mountPath: /config/controller_config.yaml
              subPath: controller_config.yaml
            - name: secret-volume
              mountPath: /config/controller_secret.yaml
              subPath: controller_secret.yaml
      serviceAccountName: avi-dns-controller
      volumes:
        - name: config-volume
          configMap:
            name: dns-controller-config
        - name: secret-volume
          secret:
            secretName: dns-controller-secret

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: avi-dns-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: avi-dns-controller-role
  namespace: default
rules:
  - apiGroups: ["akodns.vmware.com"]
    resources: ["avidnsrecords"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: avi-dns-controller-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: avi-dns-controller
    namespace: default
roleRef:
  kind: Role
  name: avi-dns-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-controller-secret
  namespace: default
type: Opaque
stringData:
  username: "admin"
  password: "VMware1!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-controller-config
  namespace: default
data:
  controller_ip: "192.168.1.100"
  tenant: "admin"
  api_path: "/api/dnsrecord"
  api_version: "22.1.2"

